p8105_hw6_cr3442
================
Cheng Rao
2024-12-02

# Problem 1

First import the data.  

  
Then take a look of the regression.  

``` r
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(alpha = .3) +
  geom_smooth(method = "lm",se = F)
```

    ## `geom_smooth()` using formula = 'y ~ x'

<img src="p8105_hw6_cr3442_files/figure-gfm/rnoaa_reg-1.png" width="100%" />  

Let’s bootstraping.  

``` r
weather_boot = 
  weather_df %>% 
  bootstrap(n = 5000) %>%
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::tidy),
    glanced = map(models, broom::glance)
    ) %>% 
  select(-strap, -models) %>% 
  unnest(c(results, glanced), names_repair = "unique") %>% 
  select(.id, term, estimate, r.squared) %>% 
  mutate(
    term = str_replace(term, "\\(Intercept\\)", "intercept")
  ) %>% 
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) %>% 
  mutate(
    intersection = log(intercept * tmin),
    .id = as.numeric(.id)
  ) %>% 
  select(-intercept, -tmin)
```

    ## New names:
    ## • `statistic` -> `statistic...5`
    ## • `p.value` -> `p.value...6`
    ## • `statistic` -> `statistic...10`
    ## • `p.value` -> `p.value...11`

Let’s plot the distribution of r square.  

``` r
weather_boot %>% 
  ggplot(aes(x = r.squared)) +
  geom_density() +
  labs(
    title = "Distribution of Estimates of R-squared",
    x = "R-square estimates",
    y = "Density"
  ) +
  scale_x_continuous(
    breaks = seq(.85,.95,.01)
  )
```

<img src="p8105_hw6_cr3442_files/figure-gfm/rsquare_plt-1.png" width="100%" />  
Let’s plot the distribution of intersection, while intersection = log(β0
\* β1).  

``` r
weather_boot %>% 
  ggplot(aes(x = intersection)) +
  geom_density() +
  labs(
    title = "Distribution of Estimates of Coefficients Intersections",
    x = "Coefficients Estimates Intersection",
    y = "Density"
  ) +
  scale_x_continuous(
    breaks = seq(1.90, 2.15, .02)
  )
```

<img src="p8105_hw6_cr3442_files/figure-gfm/unnamed-chunk-1-1.png" width="100%" />  
Finally, lets calculate and report the 95% confidence interval.  

``` r
ci_r_squared = quantile(weather_boot$r.squared, c(0.025, 0.975))
ci_intersection = quantile(weather_boot$intersection, c(0.025, 0.975))

ci_r_squared
```

    ##  2.5% 97.5% 
    ## 0.894 0.927

``` r
ci_intersection
```

    ##  2.5% 97.5% 
    ##  1.96  2.06

**Comments:**  
The distribution of estimated r-squared is approximately normal. With
the mean 0.912 and median 0.912. And the standard error of this
distribution is 0.008. Ranging from 0.876 to 0.937.  
  
The distribution of the natural log of the intersection of estimated
coefficients is approximately normal. With the mean 2.013 and median
2.013. And the standard error of this distribution is 0.024. Ranging
from 1.913 to 2.097.  
  
With 95% confidence, the r-squared value, which measures the goodness of
fit of the regression model, lies between 0.894 and 0.927. With 95%
confidence, the value of log(β0 \* β1), which reflects the logarithm of
the product of the intercept and slope coefficients, lies between 1.96
and 2.06.
